version: "2"

formats:
  - pdf
  - epub

build:
  os: "ubuntu-22.04"
  tools:
    python: "3.10"
  apt_packages:
    - abcm2ps

python:
  install:
    - requirements: docs/requirements.txt

sphinx:
  configuration: docs/source/conf.py
