version: "2"

formats:
  - pdf
  - epub

build:
  os: "ubuntu-22.04"
  tools:
    python: "3.10"

build:
  wipe_environment: true

python:
  install:
    - requirements: docs/requirements.txt

sphinx:
  configuration: docs/source/conf.py
